name: Convert YAML to CSV and Tag

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml pandas

      - name: List files for debugging
        run: ls -R

      - name: Convert YAML to CSV
        run: python scripts/convert_yaml_to_csv.py

      - name: Upload CSV file
        uses: actions/upload-artifact@v2
        with:
          name: converted-csv
          path: data.csv

      - name: Create Git tag
        env:
          GITHUB_TOKEN: ghp_oflofhy77twX429LFQRN6vfnkolOBa1THALP
        run: |
          git config --local user.email "dariswk25@gmail.com"
          git config --local user.name "daris"
          git tag -a v${{ github.run_number }} -m "Tagging build ${{ github.run_number }}"
          git push origin v${{ github.run_number }} --follow-tags

